const initialProducts = [
  {
    id: 201,
    name: "AgroShield Max Insecticide",
    img: "./imgs/agro-products/product1.jpg",
    description: {
      brand: "AgroShield",
      volume: "1L",
      formulation: "Emulsifiable Concentrate (EC)",
      activeIngredient: "Cypermethrin 10%",
      cropType: "Vegetables, Rice",
      usageRate: "2ml per L of water",
      content: [
        "Fast-acting protection against a wide range of crop-damaging insects.",
        "Effectively controls aphids, caterpillars, whiteflies, and beetles.",
        "Long residual effect ensuring protection for up to 14 days.",
        "Easy to apply with sprayers and compatible with most fertilizers.",
        "Approved by the Department of Agriculture for safe use on edible crops.",
      ],
    },
    price: 779,
    category: "insecticide",
    sellerId: 101,
    added: "2024-10-15",
    sold: 21,
    available: 47,
  },

  {
    id: 202,
    name: "NutriGrow NPK 20-20-20",
    img: "./imgs/agro-products/product2.jpg",
    description: {
      brand: "NutriGrow",
      volume: "5kg",
      formulation: "Water-Soluble Powder",
      activeIngredient: "NPK 20-20-20",
      cropType: "Fruits, Vegetables, Cereals",
      usageRate: "5g per liter of water",
      content: [
        "Balanced nutrient supply for all stages of crop development.",
        "Enhances root, stem, and leaf growth simultaneously.",
        "Highly soluble and easy to mix with irrigation systems.",
        "Improves yield quality and quantity in field and greenhouse settings.",
        "Safe for use throughout the growing season, promotes strong flowering.",
      ],
    },
    price: 1999,
    category: "fertilizer",
    sellerId: 102,
    added: "2024-03-15",
    sold: 26,
    available: 22,
  },

  {
    id: 203,
    name: "BioGuard Fungus Stop",
    img: "./imgs/agro-products/product3.jpg",
    description: {
      brand: "BioGuard",
      volume: "500ml",
      formulation: "Liquid Suspension (SC)",
      activeIngredient: "Azoxystrobin 11% + Tebuconazole 18.3%",
      cropType: "Wheat, Grapes, Tomatoes",
      usageRate: "1.5ml per L of water",
      content: [
        "Dual-mode action fungicide for rapid and long-term protection.",
        "Targets downy mildew, rust, blights, and powdery mildew.",
        "Quick absorption into plant system ensures lasting effect.",
        "Resistance management friendly with rotating use.",
        "Improves plant vigor and disease tolerance.",
      ],
    },
    price: 590,
    category: "fungicide",
    sellerId: 102,
    added: "2024-08-16",
    sold: 18,
    available: 88,
  },

  {
    id: 204,
    name: "RootBoost Micronutrient Mix",
    img: "./imgs/agro-products/product4.jpg",
    description: {
      brand: "RootBoost",
      volume: "2kg",
      formulation: "Chelated Micronutrient Powder",
      activeIngredient: "Zn, Mn, Fe, Cu, B (EDTA Chelated)",
      cropType: "All Crops",
      usageRate: "4g per L of water or as foliar spray",
      content: [
        "Enhances root development and shoot vigor.",
        "Prevents and corrects micronutrient deficiencies.",
        "Chelated formula ensures fast absorption and mobility.",
        "Improves flowering and fruit set in horticultural crops.",
        "Ideal for use in drip, foliar, and soil application systems.",
      ],
    },
    price: 3899,
    category: "micronutrient",
    sellerId: 102,
    added: "2024-09-26",
    sold: 57,
    available: 94,
  },

  {
    id: 205,
    name: "PlantRx Supreme Bio-Stimulant",
    img: "./imgs/agro-products/product5.jpg",
    description: {
      brand: "PlantRx",
      volume: "1L",
      formulation: "Liquid",
      activeIngredient: "Seaweed Extract + Humic Acid",
      cropType: "Vegetables, Orchards, Field Crops",
      usageRate: "3ml per L of water",
      content: [
        "Stimulates plant metabolism and growth hormones.",
        "Boosts resistance against drought, salinity, and stress.",
        "Increases nutrient uptake and chlorophyll production.",
        "Improves yield quality and flowering intensity.",
        "Environment-friendly and non-toxic to beneficial organisms.",
      ],
    },
    price: 799,
    category: "bio-stimulant",
    sellerId: 102,
    added: "2024-09-09",
    sold: 20,
    available: 23,
  },

  {
    id: 206,
    name: "CropShield Herbicide",
    img: "./imgs/agro-products/product6.jpg",
    description: {
      brand: "CropShield",
      volume: "500ml",
      formulation: "Soluble Liquid (SL)",
      activeIngredient: "Glyphosate 41%",
      cropType: "Non-crop, Pre-planting",
      usageRate: "10ml per L of water",
      content: [
        "Non-selective, systemic herbicide for total weed control.",
        "Effectively targets annual and perennial weeds.",
        "Absorbed through leaves and translocated to roots.",
        "Rain-fast within 6 hours, suitable for pre-sowing treatment.",
        "Ideal for clearing land and preparing seedbeds.",
      ],
    },
    price: 354,
    category: "herbicide",
    sellerId: 102,
    added: "2021-09-14",
    sold: 93,
    available: 84,
  },

  {
    id: 207,
    name: "GreenLeaf Foliar Feed",
    img: "./imgs/agro-products/product7.jpg",
    description: {
      brand: "GreenLeaf",
      volume: "1kg",
      formulation: "Powder",
      activeIngredient: "NPK 19-19-19 + TE",
      cropType: "Vegetables, Flowers, Fruits",
      usageRate: "5g per L of water",
      content: [
        "Water-soluble foliar fertilizer for rapid nutrient absorption.",
        "Enhances photosynthesis and vegetative growth.",
        "Promotes fruit development and improves taste/appearance.",
        "Contains micronutrients for complete plant health.",
        "Ideal during flowering and fruiting stages for better yield.",
      ],
    },
    price: 844,
    category: "fertilizer",
    sellerId: 102,
    added: "2025-01-10",
    sold: 53,
    available: 31,
  },

  {
    id: 208,
    name: "EcoProtect Organic Pesticide",
    img: "./imgs/agro-products/product8.jpg",
    description: {
      brand: "EcoProtect",
      volume: "500ml",
      formulation: "Organic Oil Blend",
      activeIngredient: "Neem Oil 300 ppm",
      cropType: "Organic Farms, Home Gardens",
      usageRate: "3ml per L of water",
      content: [
        "Natural pest control with no harmful residue.",
        "Repels and controls whiteflies, thrips, mites, and aphids.",
        "Safe for bees, earthworms, and beneficial insects.",
        "Improves plant immunity and resistance naturally.",
        "Certified for organic farming and eco-friendly practices.",
      ],
    },
    price: 699,
    category: "organic-pesticide",
    sellerId: 102,
    added: "2024-08-30",
    sold: 29,
    available: 27,
  },
    {
    id: 209,
    name: "NemaKill Nematicide",
    img: "./imgs/agro-products/product9.jpg",
    description: {
      brand: "SoilGuard",
      volume: "1L",
      formulation: "Liquid",
      activeIngredient: "Fluensulfone 2%",
      cropType: "Potato, Tomato, Carrot",
      usageRate: "2-3ml per L of water",
      content: [
        "Effectively controls root-knot and cyst nematodes.",
        "Reduces nematode population and improves root health.",
        "Easy soil drench application, no phytotoxicity.",
        "Enhances yield and protects root zones for extended periods.",
        "Recommended pre-planting or at early crop stage.",
      ],
    },
    price: 1099,
    category: "nematicide",
    sellerId: 103,
    added: "2024-11-01",
    sold: 12,
    available: 33,
  },

  {
    id: 210,
    name: "RapidRoot Seed Treatment",
    img: "./imgs/agro-products/product10.jpg",
    description: {
      brand: "SeedMax",
      volume: "250g",
      formulation: "Powder",
      activeIngredient: "Thiram 75%",
      cropType: "Cereals, Pulses, Oilseeds",
      usageRate: "3g per kg of seed",
      content: [
        "Protects seeds from fungal infections and damping-off.",
        "Promotes uniform germination and early seedling vigor.",
        "Compatible with most bio-fertilizers and micronutrients.",
        "Dust-free formula with long shelf life.",
        "Ideal for organic and conventional farming setups.",
      ],
    },
    price: 249,
    category: "seed-treatment",
    sellerId: 101,
    added: "2025-01-12",
    sold: 61,
    available: 49,
  },

  {
    id: 211,
    name: "ProGro Plant Growth Regulator",
    img: "./imgs/agro-products/product11.jpg",
    description: {
      brand: "ProGro",
      volume: "250ml",
      formulation: "Liquid",
      activeIngredient: "Gibberellic Acid 0.001%",
      cropType: "Grapes, Paddy, Sugarcane",
      usageRate: "1ml per L of water",
      content: [
        "Stimulates cell elongation and flowering.",
        "Increases fruit size and improves crop uniformity.",
        "Boosts photosynthesis and chlorophyll content.",
        "Use during vegetative or flowering stage as advised.",
        "Promotes earlier harvest and better market value.",
      ],
    },
    price: 180,
    category: "growth-regulator",
    sellerId: 102,
    added: "2024-07-25",
    sold: 38,
    available: 71,
  },

  {
    id: 212,
    name: "RhizoBio Bio-Fertilizer",
    img: "./imgs/agro-products/product12.jpg",
    description: {
      brand: "RhizoBio",
      volume: "1L",
      formulation: "Liquid Suspension",
      activeIngredient: "Rhizobium sp. (1×10⁹ CFU/ml)",
      cropType: "Legumes (Soybean, Pea, Lentil)",
      usageRate: "5ml per kg seed or 500ml per acre",
      content: [
        "Biological nitrogen fixation for legume crops.",
        "Improves root nodulation and reduces chemical fertilizer need.",
        "Enhances soil microbial health and sustainability.",
        "Certified organic input; boosts overall soil fertility.",
        "Apply with seeds or as root drench.",
      ],
    },
    price: 370,
    category: "bio-fertilizer",
    sellerId: 101,
    added: "2024-10-05",
    sold: 24,
    available: 58,
  },

  {
    id: 213,
    name: "K+Max Potassium Booster",
    img: "./imgs/agro-products/product13.jpg",
    description: {
      brand: "AgroNutrient",
      volume: "5kg",
      formulation: "Granules",
      activeIngredient: "Potassium Sulphate (SOP)",
      cropType: "Fruit Crops, Sugarcane",
      usageRate: "3kg per acre",
      content: [
        "Improves fruit size, sweetness, and shelf life.",
        "Essential for photosynthesis and water regulation.",
        "Chloride-free formula ideal for chloride-sensitive crops.",
        "Boosts plant immunity against stress and disease.",
        "Apply during fruiting and ripening stages.",
      ],
    },
    price: 1580,
    category: "fertilizer",
    sellerId: 103,
    added: "2024-06-12",
    sold: 32,
    available: 45,
  },

  {
    id: 214,
    name: "TrichoSafe Soil Protector",
    img: "./imgs/agro-products/product14.jpg",
    description: {
      brand: "BioGuard",
      volume: "1kg",
      formulation: "Wettable Powder",
      activeIngredient: "Trichoderma viride 1×10⁸ CFU/g",
      cropType: "All Crops",
      usageRate: "2.5kg per acre or 10g per kg of seed",
      content: [
        "Biological control against soil-borne fungal pathogens.",
        "Improves root colonization and disease resistance.",
        "Enhances organic matter decomposition in soil.",
        "Safe for organic farming and eco-restoration.",
        "Improves overall soil health and crop yield.",
      ],
    },
    price: 630,
    category: "bio-fungicide",
    sellerId: 101,
    added: "2025-01-02",
    sold: 19,
    available: 41,
  },

  {
    id: 215,
    name: "AminoGold Foliar Spray",
    img: "./imgs/agro-products/product15.jpg",
    description: {
      brand: "GoldCrop",
      volume: "500ml",
      formulation: "Liquid",
      activeIngredient: "Amino Acids + Vitamins",
      cropType: "All Crops",
      usageRate: "2ml per L of water",
      content: [
        "Improves plant stress tolerance and growth rate.",
        "Boosts enzyme activity and protein synthesis.",
        "Enhances absorption of other nutrients.",
        "Great for transplant shock recovery.",
        "Can be used along with fertilizers and pesticides.",
      ],
    },
    price: 525,
    category: "foliar-spray",
    sellerId: 102,
    added: "2024-11-07",
    sold: 44,
    available: 52,
  },

  {
    id: 216,
    name: "BactoPower Bio Control",
    img: "./imgs/agro-products/product16.jpg",
    description: {
      brand: "BactoLife",
      volume: "1L",
      formulation: "Liquid",
      activeIngredient: "Bacillus subtilis (1×10⁹ CFU/ml)",
      cropType: "Vegetables, Ornamentals, Fruits",
      usageRate: "5ml per L or 1L per acre",
      content: [
        "Biological control agent for bacterial and fungal diseases.",
        "Increases plant resistance and microbial activity in rhizosphere.",
        "Compatible with organic systems and IPM practices.",
        "Non-toxic and safe for pollinators and beneficial insects.",
        "Enhances plant vigor and reduces pathogen load.",
      ],
    },
    price: 870,
    category: "bio-control",
    sellerId: 103,
    added: "2024-12-15",
    sold: 27,
    available: 37,
  },


  {
    id: 217,
    name: "Honor Magic V3",
    img: "./imgs/smartphones/phone17.jpg",
    description: {
      brand: "Honor",
      screensize: "7.92",
      battery: 5150,
      maincamera: 50,
      soc: "Qualcomm SM8650-AB Snapdragon 8 Gen 3",
      os: "android 14",
      ram: 12,
      storage: 512,
      res: "2156 x 2344",
      refreshrate: 120,
      content: [
        `[WORLD'S THINNEST & LIGHTEST AI FOLDABLE SMARTPHONE] - Elevate your lifestyle with the world’s thinnest and lightest foldable smartphone, powered by advanced AI technology. Designed for those who seek sophistication and cutting-edge innovation, this device offers a range of intelligent AI features, all wrapped in unparalleled style.`,
        `[BRILLIANT FOLDABLE DISPLAY] - Enjoy a 7.92-INCH FOLDABLE LTPO AMOLED DISPLAY with 1 BILLION COLORS, DOLBY VISION, and a 120HZ REFRESH RATE, perfect for watching Reels, movies, gaming, and reading. The 6.43-INCH outer display delivers an impressive 5000 NITS of brightness for clear visibility in any light, while advanced eye protection ensures a comfortable viewing experience.`,
        `[POWERFUL AI-CHIPSET DRIVEN PERFORMANCE] - Experience lightning-fast speeds and smooth multitasking with the QUALCOMM SNAPDRAGON 8 GEN 3 CHIPSET (4NM) combined with 12GB RAM and 512GB STORAGE. This AI-driven powerhouse excels in handling daily tasks and delivers exceptional gaming performance with ease.`,
        `[PRO-LEVEL TRIPLE AI CAMERA SYSTEM] - Capture every moment in EXTRAORDINARY DETAIL with a 50MP WIDE CAMERA, 50MP PERISCOPE TELEPHOTO with 100X OPTICAL ZOOM, and a 40MP ULTRA-WIDE LENS. Enhance your photography with AI-MOTION SENSING and AI AUTO CAPTURE, ensuring perfect shots are automatically captured. Record STUNNING 4K VIDEOS with ADVANCED STABILIZATION for professional-quality results.`,
        `[ADVANCED BATTERY & WATER-RESISTANT DESIGN] - Stay powered all day with a 5150MAH BATTERY featuring 66W WIRED CHARGING, 50W WIRELESS CHARGING, and 5W REVERSE WIRED CHARGING. Built with [IPX8 WATER RESISTANCE (UP TO 2.5M FOR 30 MINUTES)] and ANTI SCRATCH NANO CRYSTAL FIELD PROTECTION for the outer glass, this foldable smartphone is designed for both durability and style in any environment.`,
      ],
    },
    price: 73950,
    category: "smartphones",
    sellerId: 102,
    added: "2024-09-27",
    sold: 63,
    available: 61,
  },
  {
    id: 218,
    name: "realme C75",
    img: "./imgs/smartphones/phone18.jpg",
    description: {
      brand: "Realme",
      screensize: "6.72",
      battery: 6000,
      maincamera: 50,
      soc: "Mediatek Helio G92 Max 3",
      os: "android 14",
      ram: 8,
      storage: 256,
      res: "1080 x 2400",
      refreshrate: 90,
      content: [
        `[IP69 Dust & Water Resistance] IP66/IP68/IP69 All in One.`,
        `[5828mAh Massive Battery] Embrace unstoppable energy. The realme C75 features a 5828mAh massive battery, which is about 20% larger than the average battery capacity. Power bank-level battery life puts an end to battery anxiety once and for all.`,
        `[Smart AI experience, Mini Capsule 3.0/AI Clear Face/AI Smart Loop] Grab now pops up with Mini Capsule! The realme C75 introduces the all-new Mini Capsule 3.0, featuring the first real-time Grab status bar notification. Leveraging the capabilities of Al algorithms, the realme C75 enhances the clarity of blurred faces in photos. Through Al enhancement, facial details are restored, making your photos more vivid and lifelike.`,
        `[90Hz Refresh Rate and 6.72" FHD Display] 2400 x 1080 FHD display delivers sharp and clear visuals for an enhanced viewing experience. Enjoy smooth scrolling and responsiveness that elevates gaming, streaming, and everyday tasks.`,
        `[50MP Super Clear Camera] Capture every moment in breathtaking detail. With algorithm optimizations, this camera takes sharp, vibrant photos. The 50MP super clear camera and advanced shadow removal algorithms ensure clear and detailed document capture.`,
      ],
    },
    price: 10245,
    category: "smartphones",
    sellerId: 102,
    added: "2025-02-25",
    sold: 92,
    available: 88,
  },
  {
    id: 219,
    name: "Realme C63",
    img: "./imgs/smartphones/phone19.jpg",
    description: {
      brand: "Realme",
      screensize: "6.75",
      battery: 5000,
      maincamera: 50,
      soc: "Unisoc Tiger T612",
      os: "android 14",
      ram: 6,
      storage: 128,
      res: "720 x 1600",
      refreshrate: 90,
      content: [`Brand: realme`],
    },
    price: 6499,
    category: "smartphones",
    sellerId: 102,
    added: "2024-06-30",
    sold: 16,
    available: 35,
  },

  {
    id: 220,
    name: "realme Note 50",
    img: "./imgs/smartphones/phone20.jpg",
    description: {
      brand: "Realme",
      screensize: "6.74",
      battery: 5000,
      maincamera: 13,
      soc: "Unisoc Tiger T612",
      os: "android 13",
      ram: 3,
      storage: 64,
      res: "720 x 1600",
      refreshrate: 90,
      content: [`realme`, `Smart Phone`, `Note 50`],
    },
    price: 4975,
    category: "smartphones",
    sellerId: 102,
    added: "2024-05-16",
    sold: 85,
    available: 69,
  },

  {
    id: 221,
    name: "Oppo Reno 13F",
    img: "./imgs/smartphones/phone21.jpg",
    description: {
      brand: "Oppo",
      screensize: "6.67",
      battery: 5800,
      maincamera: 50,
      soc: "Qualcomm SM6450 Snapdragon 6 Gen 1",
      os: "android 15",
      ram: 12,
      storage: 256,
      res: "1080 x 2400",
      refreshrate: 120,
      content: [
        `Screen size in inches: 6.67 inches. Display resolution: 1080 x 2400 pixels, 20:9 ratio (395 ppi pixel density)`,
        `Processor chipset: Qualcomm SM6450 Snapdragon 6 Gen 1 (4 nm)`,
        `Internal memory: 256 GB, RAM: 12 GB RAM`,
        `Video recording type: 4K@30fps, 1080p@30/60/120fps, gyro-EIS, OIS`,
        `Front camera: 32 MP32 MP, f/2.4, 22mm (wide), 1/2.74", 0.8 µm`,
      ],
    },
    price: 18888,
    category: "smartphones",
    sellerId: 102,
    added: "2025-02-12",
    sold: 88,
    available: 19,
  },

  {
    id: 222,
    name: "OPPO A3X",
    img: "./imgs/smartphones/phone22.jpg",
    description: {
      brand: "Oppo",
      screensize: "6.67",
      battery: 5100,
      maincamera: 8,
      soc: "Qualcomm SM-6115 Snapdragon 6s 4G Gen1",
      os: "android 14",
      ram: 4,
      storage: 64,
      res: "720 x 1604",
      refreshrate: 90,
      content: [
        `DISPLAY :16.94 cm (6.67"Inch) HD+ LCD 90Hz Ultra Bright Display to greatly improve the smoothness of screen touches ,with Screen-to-body ratio of 89.9% for better viewing experience.`,
        `CAMERA : Ultra-Clear Camera 8MP Rear camera |5MP Front Selfie Camera`,
        `MEMORY, STORAGE,SIM & PROCESSOR : 4GB RAM|64 GB ROM | Dual 4G Sim Slot |Latest Android 14 Operating System and ColorOS 14.0 System Platform with Snapdragon 6s 4G Gen1 .`,
        `FAST CHARGING & BATTERY : 45W SuperVOOC charging enable fast and efficient charging .It have 5100mAh hyper energy battery`,
        `SHOCK RESISTANCE : It has Straight-corner bezel design, with chamfering on back cover edges to ensure a comfortable grip.The screen uses double-tempering glass making it shock resistance device`,
      ],
    },
    price: 5499,
    category: "smartphones",
    sellerId: 102,
    added: "2024-11-04",
    sold: 36,
    available: 58,
  },

  {
    id: 223,
    name: "Infinix Smart 9",
    img: "./imgs/smartphones/phone23.jpg",
    description: {
      brand: "Infinix",
      screensize: "6.7",
      battery: 5000,
      maincamera: 13,
      soc: "Mediatek Helio G81",
      os: "android 14 go",
      ram: 8,
      storage: 128,
      res: "720 x 1600",
      refreshrate: 120,
      content: [
        `120Hz Punch-Hole Display with Dynamic Bar`,
        `Helio G81 Processor & 48 Month Performance TÜV Fluency`,
        `Dual Speakers 300% Ultra Volume`,
      ],
    },
    price: 4399,
    category: "smartphones",
    sellerId: 102,
    added: "2024-10-06",
    sold: 20,
    available: 60,
  },
  {
    id: 224,
    name: "Infinix Smart 8",
    img: "./imgs/smartphones/phone24.jpg",
    description: {
      brand: "Infinix",
      screensize: "6.6",
      battery: 5000,
      maincamera: 13,
      soc: "Unisoc T606",
      os: "android 13",
      ram: 4,
      storage: 64,
      res: "720 x 1612",
      refreshrate: 90,
      content: [
        `6.6" HD+ Display Screen`,
        `Up to 2GB Extended RAM+64 GB Storage`,
        `5000mAh Long-standing Battery Type-C Charging`,
        `Side Fingerprint + Face Fast Unlock`,
        `13MP Dual Al Camera with Ring Flashlight`,
      ],
    },
    price: 3777,
    category: "smartphones",
    sellerId: 102,
    added: "2024-10-05",
    sold: 65,
    available: 80,
  },
  {
    id: 225,
    name: "Infinix Hot 50i",
    img: "./imgs/smartphones/phone25.jpg",
    description: {
      brand: "Infinix",
      screensize: "6.7",
      battery: 5000,
      maincamera: 48,
      soc: "Mediatek Helio G81",
      os: "android 14",
      ram: 12,
      storage: 128,
      res: "720 x 1600",
      refreshrate: 120,
      content: [
        `Enjoy a stunning 120Hz 6.7-inch punch-hole display for smooth visuals and an immersive viewing experience`,
        `Experience enhanced performance with the Helio G81 processor, certified for 48 months of fluency`,
        `Immerse yourself in sound with dual speakers that deliver 300 percent ultra volume for an incredible audio experience`,
        `Stay powered throughout your day with an 18W FastCharge feature and a robust 5000mAh battery`,
        `48MP crystal-clear camera and brighten up emergencies with a powerful 5m LED flashlight`,
      ],
    },
    price: 5275,
    category: "smartphones",
    sellerId: 102,
    added: "2024-10-23",
    sold: 93,
    available: 12,
  },

  // laptops
  {
    id: 301,
    name: "Dell Vostro 3520",
    img: "./imgs/laptops/laptop1.jpg",
    description: {
      brand: "dell",
      cpu: "Intel i5-1235U",
      gpu: "Intel UHD Graphics",
      ram: 8,
      storage: 256,
      res: "1920 x 1080",
      refreshrate: 120,
      content: [
        `12th Generation Intel Core i5-1235U (12MB Cache, up t o 4.4 GHz, 10 cores)`,
        `8GB DDR4 2666MHz`,
        `56GB M.2 PCIe NVMe Solid State Drive`,
        `ealtek Wi-Fi 5 RTL8821CE, 1x1 , 802.11ac, MU-MIMO, Bluetooth wireless card`,
      ],
    },
    price: 24852,
    category: "laptops",
    sellerId: 201,
    added: "2023-12-16",
    sold: 37,
    available: 28,
  },

  {
    id: 302,
    name: "HP Victus Gaming Laptop 15-fb1004ne",
    img: "./imgs/laptops/laptop2.jpg",
    description: {
      brand: "hp",
      cpu: "Ryzen 5 7335HS",
      gpu: "Nvidia GeForce RTX 2050",
      ram: 16,
      storage: 512,
      res: "1920 x 1080",
      refreshrate: 144,
      content: [
        `Processor: Ryzen 5-7535HS, a capable processor for gaming and multitasking.`,
        `RAM:16GB, providing ample memory for multitasking and resource-intensive tasks.`,
        `Graphics: NVIDIA GeForce GTX 1650 graphics card for entry-level gaming performance.`,
        `Display: 15.6-inch FHD IPS display with 60Hz refresh rate for standard visuals.`,
      ],
    },
    price: 31399,
    category: "laptops",
    sellerId: 201,
    added: "2024-04-04",
    sold: 17,
    available: 26,
  },

  {
    id: 303,
    name: "Apple Macbook Air 2020 Model",
    img: "./imgs/laptops/laptop3.jpg",
    description: {
      brand: "apple",
      cpu: "Apple M1",
      gpu: "M1 7-core GPU",
      ram: 8,
      storage: 256,
      res: "2560 x 1664",
      refreshrate: 60,
      content: [
        `Apple's M1 chip redefines our thinnest and lightest laptop. The CPU is up to 3.5 times more powerful. Graphics, up to five times faster`,
        `Enjoy absolute comfort from A to Z. In addition to typing at your leisure, with the pre programmed shortcuts on this keyboard you can instantly access the features you use the most`,
        `One touch is enough to lock and unlock your MacBook Air`,
        `Enjoy the views. Rest your eyes. The MacBook Air knows how to automatically adjust the white point of the screen according to the ambient color temperature, so it is more comfortable to look at`,
        `The M1 chip carries the fastest CPU we've ever developed`,
      ],
    },
    price: 36072,
    category: "laptops",
    sellerId: 201,
    added: "2020-11-09",
    sold: 37,
    available: 23,
  },
  {
    id: 304,
    name: "DELL G15 5530 Gaming Laptop",
    img: "./imgs/laptops/laptop4.jpg",
    description: {
      brand: "dell",
      cpu: "Intel Core i7-13650HX",
      gpu: "NVIDIA GeForce RTX 3050",
      ram: 16,
      storage: 512,
      res: "1920 x 1080",
      refreshrate: 120,
      content: [
        `DELL G15 5530 Gaming Laptop - 13th Intel Core i7-13650HX (24 MB cache, 1 4 core, up to 4.90 GHz), NVIDIA GeForce RTX 3050 6GB GDDR6 Graphics, 16GB (2x8GB) DDR5 4800MHz RAM, 512GB M.2 PCIe NVMe SSD, 15.6" FHD (1920x1080) 120Hz, 3-Cell Battery 56WHr (Integrated) , 240W AC Adapter, English Arabic Qwerty 4-Zone RGB Backlit Keyboard with Numeric Keypad and G-Key, UBUNTU - Dark Shadow Gray`,
      ],
    },
    price: 51720,
    category: "laptops",
    sellerId: 201,
    added: "2023-11-26",
    sold: 35,
    available: 27,
  },

  {
    id: 305,
    name: "Lenovo Legion 5",
    img: "./imgs/laptops/laptop5.jpg",
    description: {
      brand: "lenovo",
      cpu: "Intel i7-11800H",
      gpu: "NVIDIA RTX 3070 8GB",
      ram: 16,
      storage: 1024,
      res: "2560 x 1440",
      refreshrate: 165,
      content: [
        `Brand: Lenovo`,
        `Hard disk Size: 1 TB`,
        `Operating system: DOS`,
        `Cpu model Speed: 4.6 GHz`,
        `Brand: Lenovo`,
        `Operating system: DOS`,
        `Cpu model Family: core_i7_family`,
      ],
    },
    price: 58301,
    category: "laptops",
    sellerId: 201,
    added: "2022-05-30",
    sold: 18,
    available: 30,
  },

  {
    id: 306,
    name: "ASUS Vivobook S 14 Flip",
    img: "./imgs/laptops/laptop6.jpg",
    description: {
      brand: "asus",
      cpu: "AMD Ryzen 7 7730U",
      gpu: "AMD Radeon Graphics",
      ram: 8,
      storage: 512,
      res: "1920 x 1200",
      refreshrate: 60,
      content: [
        `The super-versatile convertible with a 360-degree hinge that gives you the freedom to work or play, your way`,
        `Enjoy the smooth performance of the AMD Ryzen 7 7730U processor, 8GB DDR4 RAM and fast 512 SSD storage`,
        `Features amazing 14-inch Nano Edge 60 Hz FHD plus touchscreen display with 16:10 aspect ratio`,
        `Features all the I/O ports you need, connecting all your existing peripherals, displays and projectors is a cinch`,
        `Enjoy uninterrupted on-the-go productivity with the long-lasting 50 Wh battery`,
      ],
    },
    price: 40300,
    category: "laptops",
    sellerId: 201,
    added: "2024-04-19",
    sold: 38,
    available: 20,
  },

  {
    id: 307,
    name: "Lenovo LOQ 15IRX9 Gaming",
    img: "./imgs/laptops/laptop7.jpg",
    description: {
      brand: "lenovo",
      cpu: "Intel i7-14700HX",
      gpu: "NVIDIA GeForce RTX 4060",
      ram: 16,
      storage: 1024,
      res: "1920 x 1200",
      refreshrate: 144,
      content: [
        `Battery : Integrated 60Wh`,
        `Power Adapter : 230W Slim Tip (3-pin)`,
        `Camera : FHD 1080p with E-shutter`,
        `Stereo speakers 2W x2 optimized with Nahimic Audio`,
        `AI Chip: LA1 ( Artificial Intelengce)`,
      ],
    },
    price: 64999,
    category: "laptops",
    sellerId: 201,
    added: "2024-11-05",
    sold: 5,
    available: 31,
  },

  {
    id: 308,
    name: "Lenovo LOQ 15IRX9 Gaming",
    img: "./imgs/laptops/laptop8.jpg",
    description: {
      brand: "lenovo",
      cpu: "Intel Core i7-13650HX ",
      gpu: "NVIDIA GeForce RTX 4050 ",
      ram: 16,
      storage: 512,
      res: "1920 x 1200",
      refreshrate: 144,
      content: [
        `Battery : Integrated 60Wh`,
        `Power Adapter : 170W Slim Tip (3-pin)`,
        `Camera : FHD 1080p with E-shutter`,
        `Stereo speakers 2W x2 optimized with Nahimic Audio`,
        `AI Chip: LA1 ( Artificial Intelengce)`,
      ],
    },
    price: 51999,
    category: "laptops",
    sellerId: 201,
    added: "2024-03-19",
    sold: 16,
    available: 45,
  },

  {
    id: 309,
    name: "Lenovo Legion 5 16IRX9 Gaming",
    img: "./imgs/laptops/laptop9.jpg",
    description: {
      brand: "lenovo",
      cpu: "Intel Core i9-14900HX",
      gpu: "NVIDIA GeForce RTX 4060",
      ram: 32,
      storage: 512,
      res: "2560 x 1600",
      refreshrate: 165,
      content: [
        `Intel Core i9-14900HX, 24C (8P + 16E) / 32T, P-core 2.2 / 5.8GHz, E-core 1.6 / 4.1GHz, 36MB`,
        `AI-Powered Gaming PC`,
        `NVIDIA GeForce RTX 4060 8GB GDDR6, Boost Clock 2370MHz, TGP 140W, 233 AI TOPS`,
        `2x 16GB SO-DIMM DDR5-5600`,
        `16" WQXGA (2560x1600) IPS 350nits Anti-glare, 100% sRGB, 165Hz, Dolby Vision, G-SYNC, Low Blue Light`,
      ],
    },
    price: 95343,
    category: "laptops",
    sellerId: 201,
    added: "2024-09-26",
    sold: 7,
    available: 29,
  },

  {
    id: 310,
    name: "ASUS TUF Gaming F15",
    img: "./imgs/laptops/laptop10.jpg",
    description: {
      brand: "asus",
      cpu: "Intel Core i7-13620H",
      gpu: "NVIDIA GeForce RTX 4060",
      ram: 8,
      storage: 1024,
      res: "1920 x 1080",
      refreshrate: 144,
      content: [
        `Powerful Intel Core i7-13620H processor for smooth gaming performance`,
        `16GB RAM for multitasking and seamless operation`,
        `Equipped with Windows 11 for the latest features and gaming optimizations`,
        `1TB SSD for fast boot-up times and ample storage for games and files`,
        `15.6-inch full HD display with a 144Hz refresh rate for smooth and immersive gaming visuals`,
      ],
    },
    price: 59500,
    category: "laptops",
    sellerId: 201,
    added: "2024-04-19",
    sold: 30,
    available: 33,
  },

  {
    id: 311,
    name: "Lenovo Legion 5 15ACH6 Gaming",
    img: "./imgs/laptops/laptop11.jpg",
    description: {
      brand: "lenovo",
      cpu: "amd Ryzen 5-5600H",
      gpu: "NVIDIA GeForce RTX 3050 Ti",
      ram: 16,
      storage: 512,
      res: "1920 x 1080",
      refreshrate: 120,
      content: [
        `Lenovo Legion 5 15ACH6 Gaming Laptop - Ryzen 5 5600H 6-Cores, 16 GB RAM, 512 GB SSD, NVIDIA GeForce RTX 3050 Ti 4GB GDDR6 Graphics, 15.6" FHD (1920x1080) IPS 120Hz, Backlit Keyboard, Windows 11`,
      ],
    },
    price: 39878,
    category: "laptops",
    sellerId: 201,
    added: "2023-02-21",
    sold: 2,
    available: 42,
  },

  {
    id: 312,
    name: "Lenovo LOQ 15ARP9 Gaming",
    img: "./imgs/laptops/laptop12.jpg",
    description: {
      brand: "lenovo",
      cpu: "amd Ryzen 5 7235HS",
      gpu: "NVIDIA GeForce RTX 3050",
      ram: 12,
      storage: 512,
      res: "1920 x 1080",
      refreshrate: 144,
      content: [
        `AMD Ryzen 5 7235HS (4C / 8T, 3.2 / 4.2GHz, 2MB L2 / 8MB L3)`,
        `Graphics: NVIDIA GeForce RTX 3050 6GB GDDR6, Boost Clock 1732MHz, TGP 95W`,
        `Memory : 12GB SO-DIMM DDR5-4800`,
        `Storage : 512GB SSD M.2 2242 PCIe 4.0x4 NVMe`,
        `Display : 15.6" FHD (1920x1080) IPS 300nits Anti-glare, 100% sRGB, 144Hz, G-SYNC`,
      ],
    },
    price: 38126,
    category: "laptops",
    sellerId: 201,
    added: "2024-12-26",
    sold: 15,
    available: 9,
  },

  // Accessories (20 products)
  // Headphones (25 products)
  {
    id: 401,
    name: "Sennheiser Consumer Audio Momentum 4",
    img: "./imgs/headphones/headphone1.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Smartphones, Laptops, Tablets, Desktops",
      Cable_Feature: "Without Cable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "780 g",
      Package_Dimensions: "21.7 x 21.5 x 6.6 cm; 780 g",
      Color_Name: "Black/Copper",
    },
    price: 19999,
    category: "headphones",
    sellerId: 303,
    added: "2024-07-04",
    sold: 4,
    available: 9,
  },
  {
    id: 402,
    name: "Sennheiser ACCENTUM Plus",
    img: "./imgs/headphones/headphone2.jpg",
    description: {
      Material: "Kunstleder Metall",
      Compatible_Devices: "Various Bluetooth-enabled devices",
      Cable_Feature: "	Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "227 g",
      Package_Dimensions: "16.5 x 4.8 x 19.5 cm; 227 g",
      Color_Name: "Accentum Plus/White",
    },
    price: 13563,
    category: "headphones",
    sellerId: 303,
    added: "2024-01-27",
    sold: 12,
    available: 5,
  },
  {
    id: 403,
    name: "Sennheiser RS 120-W On-Ear",
    img: "./imgs/headphones/headphone3.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "695 g",
      Package_Dimensions: "19.5 x 8.2 x 19 cm; 695 g",
      Color_Name: "Black/Copper",
    },
    price: 10999,
    category: "headphones",
    sellerId: 303,
    added: "2023-08-20",
    sold: 1,
    available: 10,
  },
  {
    id: 404,
    name: "Sony WH-CH520",
    img: "./imgs/headphones/headphone4.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Various Bluetooth-enabled devices",
      Cable_Feature: "Fixed",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "420 g",
      Package_Dimensions: "17.39 x 4.48 x 19.72 cm; 420 g",
      Color_Name: "Cream",
    },
    price: 2520,
    category: "headphones",
    sellerId: 303,
    added: "2023-03-10",
    sold: 12,
    available: 3,
  },
  {
    id: 405,
    name: "wireless headphone sodo sd-1004 - Black",
    img: "./imgs/headphones/headphone5.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "300 g",
      Package_Dimensions: "20 x 19.7 x 9.7 cm; 300 g",
      Color_Name: "Black",
    },
    price: 395,
    category: "headphones",
    sellerId: 303,
    added: "2023-04-01",
    sold: 6,
    available: 7,
  },
  {
    id: 406,
    name: "Year P9 ",
    img: "./imgs/headphones/headphone6.jpg",
    description: {
      Material: "Kunstleder Metall",
      Compatible_Devices: "Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "200 g",
      Package_Dimensions: "10 x 10 x 10 cm; 200 g",
      Color_Name: "White",
    },
    price: 220,
    category: "headphones",
    sellerId: 303,
    added: "2023-05-09",
    sold: 0,
    available: 11,
  },
  {
    id: 407,
    name: "Headphone Celebrat A27",
    img: "./imgs/headphones/headphone7.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "140 g",
      Package_Dimensions: "22 x 19.3 x 7.9 cm; 140 g",
      Color_Name: "Black",
    },
    price: 599,
    category: "headphones",
    sellerId: 303,
    added: "2025-02-15",
    sold: 4,
    available: 9,
  },
  {
    id: 408,
    name: "Odaban F2 RGB Gaming Headset",
    img: "./imgs/headphones/headphone8.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices:
        "PC,PlayStation 4,Xbox One, Mac,PlayStation, Windows, Xbox 360",
      Cable_Feature: "Fixed",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "280 g",
      Package_Dimensions: "35 x 35 x 20 cm; 280 g",
      Color_Name: "Black",
    },
    price: 599,
    category: "headphones",
    sellerId: 303,
    added: "2023-09-04",
    sold: 6,
    available: 6,
  },
  {
    id: 409,
    name: "JBL Tune 520BT",
    img: "./imgs/headphones/headphone9.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "235 g",
      Package_Dimensions: "10 x 10 x 10 cm; 235 g",
      Color_Name: "Black",
    },
    price: 1400,
    category: "headphones",
    sellerId: 303,
    added: "2023-09-07",
    sold: 5,
    available: 13,
  },
  {
    id: 410,
    name: "J-520 Headset Eerphone",
    img: "./imgs/headphones/headphone10.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Various Bluetooth-enabled devices",
      Cable_Feature: "Fixed",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "130 g",
      Package_Dimensions: "20 x 20 x 4 cm; 130 g",
      Color_Name: "Black",
    },
    price: 699,
    category: "headphones",
    sellerId: 303,
    added: "2025-04-11",
    sold: 2,
    available: 9,
  },
  {
    id: 411,
    name: "J-520 Headset Eerphone",
    img: "./imgs/headphones/headphone11.jpg",
    description: {
      Material: "	Faux Leather Plastic",
      Compatible_Devices: "	Devices with 3.5 mm audio jack or microphone input",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "136 g",
      Package_Dimensions: "16.51 x 6.99 x 16.51 cm; 136.08 g",
      Color_Name: "Black",
    },
    price: 540,
    category: "headphones",
    sellerId: 303,
    added: "2019-07-01",
    sold: 8,
    available: 4,
  },
  {
    id: 412,
    name: "P9 Wireless Bluetooth Headset",
    img: "./imgs/headphones/headphone12.jpg",
    description: {
      Material: "	Faux Leather Plastic",
      Compatible_Devices: "	Devices with 3.5 mm audio jack or microphone input",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "200 g",
      Package_Dimensions: "20.5 x 19.7 x 4.4 cm; 200 g",
      Color_Name: "Black",
    },
    price: 238,
    category: "headphones",
    sellerId: 303,
    added: "2023-05-09",
    sold: 9,
    available: 2,
  },
  {
    id: 413,
    name: "Anker Soundcore H30i Wireless On-Ear",
    img: "./imgs/headphones/headphone13.jpg",
    description: {
      Material: "Kunstleder Metall",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Fixed",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "135 g",
      Package_Dimensions: "23.6 x 18 x 5.3 cm; 135 g",
      Color_Name: "white",
    },
    price: 1530,
    category: "headphones",
    sellerId: 303,
    added: "2024-05-13",
    sold: 3,
    available: 7,
  },
  {
    id: 414,
    name: "NKER Soundcore Q11i ",
    img: "./imgs/headphones/headphone14.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Fixed",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "240 g",
      Package_Dimensions: "17.6 x 7.95 x 18.5 cm; 240.4 g",
      Color_Name: "Dark Grey",
    },
    price: 1999,
    category: "headphones",
    sellerId: 303,
    added: "2024-12-22",
    sold: 6,
    available: 7,
  },
  {
    id: 415,
    name: "Gaming Headset for PS5 PS4 Xbox ONE Switch ",
    img: "./imgs/headphones/headphone15.jpg",
    description: {
      Material: "	Faux Leather Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "49 g",
      Package_Dimensions: " 20.7 x 19.1 x 9.8 cm; 49 g",
      Color_Name: "camouflage",
    },
    price: 550,
    category: "headphones",
    sellerId: 303,
    added: "2021-09-25",
    sold: 4,
    available: 6,
  },
  {
    id: 416,
    name: "Ozeino GM5 Gaming Headset",
    img: "./imgs/headphones/headphone16.jpg",
    description: {
      Material: "	Faux Leather Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "50 g",
      Package_Dimensions: " 20 x 18 x 9 cm; 50 g",
      Color_Name: "blue",
    },
    price: 444,
    category: "headphones",
    sellerId: 303,
    added: "2024-02-12",
    sold: 8,
    available: 3,
  },
  {
    id: 417,
    name: "Headphone SD-1101",
    img: "./imgs/headphones/headphone17.jpg",
    description: {
      Material: "	Faux Leather Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "30 g",
      Package_Dimensions: "  20.1 x 18.3 x 9.1 cm; 30 g",
      Color_Name: "white",
    },
    price: 369,
    category: "headphones",
    sellerId: 303,
    added: "2024-06-12",
    sold: 11,
    available: 3,
  },
  {
    id: 418,
    name: "Headphone Gaming Headset for Xbox One, PS4, PC",
    img: "./imgs/headphones/headphone18.jpg",
    description: {
      Material: "	Faux Leather Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "70 g",
      Package_Dimensions: " 17 x 7 x 5 cm; 70 g",
      Color_Name: "Wired White",
    },
    price: 479,
    category: "headphones",
    sellerId: 303,
    added: "2025-02-25",
    sold: 5,
    available: 7,
  },
  {
    id: 419,
    name: "J-520 Headset Eerphone",
    img: "./imgs/headphones/headphone19.jpg",
    description: {
      Material: "	Faux Leather Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "30 g",
      Package_Dimensions: " 20.5 x 18.6 x 4.7 cm; 30 g",
      Color_Name: "White",
    },
    price: 649,
    category: "headphones",
    sellerId: 303,
    added: "2025-02-24",
    sold: 3,
    available: 11,
  },
  {
    id: 420,
    name: "RGB Gaming Headset stereo 3.5mm",
    img: "./imgs/headphones/headphone20.jpg",
    description: {
      Material: "	Faux Leather Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "100 g",
      Package_Dimensions: " 18 x 13.6 x 7.9 cm; 100 g",
      Color_Name: "black",
    },
    price: 366,
    category: "headphones",
    sellerId: 303,
    added: "2024-11-05",
    sold: 9,
    available: 4,
  },
  {
    id: 421,
    name: "Soundcore H30i Wireless ",
    img: "./imgs/headphones/headphone21.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "50 g",
      Package_Dimensions: " 23.9 x 18.8 x 9 cm; 50 g",
      Color_Name: "black",
    },
    price: 1682,
    category: "headphones",
    sellerId: 303,
    added: "2024-05-12",
    sold: 6,
    available: 6,
  },
  {
    id: 421,
    name: "Soundcore H30i Wireless ",
    img: "./imgs/headphones/headphone21.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "	Various Bluetooth-enabled devices",
      Cable_Feature: "Detachable",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "50 g",
      Package_Dimensions: " 23.9 x 18.8 x 9 cm; 50 g",
      Color_Name: "black",
    },
    price: 1682,
    category: "headphones",
    sellerId: 303,
    added: "2024-05-12",
    sold: 2,
    available: 7,
  },
  {
    id: 422,
    name: "Soundcore H30i Wireless ",
    img: "./imgs/headphones/headphone22.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Cellphones",
      Cable_Feature: "Tangle Free",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "120 g",
      Package_Dimensions: " 20.32 x 15.14 x 4.9 cm; 120 g",
      Color_Name: "White",
    },
    price: 620,
    category: "headphones",
    sellerId: 303,
    added: "2024-09-24",
    sold: 5,
    available: 3,
  },
  {
    id: 423,
    name: "SD-1102 Wireless Headset",
    img: "./imgs/headphones/headphone23.jpg",
    description: {
      Material: "Plastic",
      Compatible_Devices: "Cellphones",
      Cable_Feature: "Tangle Free",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "30 g",
      Package_Dimensions: "  21.4 x 19.7 x 8.2 cm; 30 g",
      Color_Name: "black",
    },
    price: 369,
    category: "headphones",
    sellerId: 303,
    added: "2024-12-22",
    sold: 4,
    available: 7,
  },
  {
    id: 424,
    name: "Sony mdrzx110apblack",
    img: "./imgs/headphones/headphone24.jpg",
    description: {
      Material: "Silicone",
      Compatible_Devices: "Cellphones",
      Cable_Feature: "Tangle Free",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "120 g",
      Package_Dimensions: "20.32 x 5.08 x 15.24 cm; 120 g",
      Color_Name: "black",
    },
    price: 645,
    category: "headphones",
    sellerId: 303,
    added: "2024-06-23",
    sold: 8,
    available: 6,
  },
  {
    id: 425,
    name: "Anker soundcore H30i A3012H91",
    img: "./imgs/headphones/headphone25.jpg",
    description: {
      Material: "Silicone",
      Compatible_Devices: "Cellphones",
      Cable_Feature: "Tangle Free",
      Water_Resistance_Level: "Not Water Resistant",
      Item_Weight: "65 g",
      Package_Dimensions: "25.5 x 18.5 x 6 cm; 65 g",
      Color_Name: "Red",
    },
    price: 1765,
    category: "headphones",
    sellerId: 303,
    added: "2024-05-13",
    sold: 1,
    available: 8,
  },
];

const userData = {
  admin: [
    {
      id: 1,
      name: "Admin User",
      email: "admin@shop.com",
      password: "admin123",
      role: "admin",
    },
  ],
  sellers: [
    {
      id: 101,
      name: "ElectroWorld",
      email: "seller1@yaomix.com",
      password: "sellerpass1",
      role: "seller",
      products: [201, 202],
    },
    {
      id: 102,
      name: "FashionFiesta",
      email: "seller2@yaomix.com",
      password: "sellerpass2",
      role: "seller",
      products: [203, 204],
    },
    {
      id: 201,
      name: "FashionFiesta",
      email: "seller3@yaomix.com",
      password: "sellerpass3",
      role: "seller",
      products: [203, 204],
    },
    {
      id: 303,
      name: "FashionFiesta",
      email: "seller4@yaomix.com",
      password: "sellerpass4",
      role: "seller",
      products: [203, 204],
    },
  ],
  customers: [
    {
      id: 4,
      name: "Alice Johnson",
      email: "alice@example.com",
      password: "password123",
      role: "customer",
      order_history: [1001, 1002],
      address: "123 Elm Street, NY",
    },
    {
      id: 5,
      name: "Bob Smith",
      email: "bob@example.com",
      password: "password456",
      role: "customer",
      order_history: [1003],
      address: "456 Oak Avenue, CA",
    },
    {
      id: 6,
      name: "john doe",
      email: "john@example.com",
      password: "password780",
      role: "customer",
      order_history: [],
      address: "123 Elm Street, NY",
    },
  ],
};

const orders = [
  {
    id: "order_1001",
    userId: 4,
    items: [
      {
        productId: 202,
        productName: "Samsung Galaxy A55 5G",
        quantity: 1,
        price: 19999,
        total: 19999,
      },
      {
        productId: 404,
        productName: "Sony WH-CH520",
        quantity: 1,
        price: 2520,
        total: 2520,
      },
    ],
    totalAmount: 22519,
    status: "Delivered",
    date: new Date("2024-05-10T10:30:00Z").toLocaleString(),
  },

  {
    id: "order_1002",
    userId: 4,
    items: [
      {
        productId: 301,
        productName: "Dell Vostro 3520",
        quantity: 1,
        price: 24852,
        total: 24852,
      },
    ],
    totalAmount: 24852,
    status: "Shipped",
    date: new Date("2024-06-15T14:00:00Z").toLocaleString(),
  },

  {
    id: "order_1003",
    userId: 5,
    items: [
      {
        productId: 206,
        productName: "Apple iPhone 13",
        quantity: 1,
        price: 35450,
        total: 35450,
      },
    ],
    totalAmount: 35450,
    status: "Processing",
    date: new Date("2024-07-01T09:15:00Z").toLocaleString(),
  },

  {
    id: "order_1004",
    userId: 6,
    items: [
      {
        productId: 412,
        productName: "P9 Wireless Bluetooth Headset",
        quantity: 2,
        price: 238,
        total: 476,
      },
      {
        productId: 224,
        productName: "Infinix Smart 8",
        quantity: 1,
        price: 3777,
        total: 3777,
      },
    ],
    totalAmount: 4253,
    status: "Processing",
    date: new Date("2024-07-03T11:00:00Z").toLocaleString(),
  },

  {
    id: "order_1005",
    userId: 5,
    items: [
      {
        productId: 303,
        productName: "Apple Macbook Air 2020 Model",
        quantity: 1,
        price: 36072,
        total: 36072,
      },
    ],
    totalAmount: 36072,
    status: "Processing",
    date: new Date("2024-07-04T16:45:00Z").toLocaleString(),
  },

  {
    id: "order_1006",
    userId: 4,
    items: [
      {
        productId: 210,
        productName: "Xiaomi Redmi 13",
        quantity: 1,
        price: 7390,
        total: 7390,
      },
    ],
    totalAmount: 7390,
    status: "Processing",
    date: new Date("2024-07-05T08:00:00Z").toLocaleString(),
  },

  {
    id: "order_1007",
    userId: 6,
    items: [
      {
        productId: 401,
        productName: "Sennheiser Consumer Audio Momentum 4",
        quantity: 1,
        price: 19999,
        total: 19999,
      },
      {
        productId: 417,
        productName: "Headphone SD-1101",
        quantity: 1,
        price: 369,
        total: 369,
      },
    ],
    totalAmount: 20368,
    status: "Shipped",
    date: new Date("2024-07-06T12:20:00Z").toLocaleString(),
  },

  {
    id: "order_1008",
    userId: 5,
    items: [
      {
        productId: 310,
        productName: "ASUS TUF Gaming F15",
        quantity: 1,
        price: 59500,
        total: 59500,
      },
    ],
    totalAmount: 59500,
    status: "Delivered",
    date: new Date("2024-07-07T15:00:00Z").toLocaleString(),
  },

  {
    id: "order_1009",
    userId: 4,
    items: [
      {
        productId: 215,
        productName: "Honor X7c",
        quantity: 1,
        price: 8199,
        total: 8199,
      },
      {
        productId: 216,
        productName: "Honor X5b",
        quantity: 2,
        price: 4399,
        total: 8798,
      },
    ],
    totalAmount: 16997,
    status: "Delivered",
    date: new Date("2024-07-08T10:00:00Z").toLocaleString(),
  },

  {
    id: "order_1010",
    userId: 6,
    items: [
      {
        productId: 425,
        productName: "Anker soundcore H30i A3012H91",
        quantity: 1,
        price: 1765,
        total: 1765,
      },
    ],
    totalAmount: 1765,
    status: "Processing",
    date: new Date("2024-07-09T11:30:00Z").toLocaleString(),
  },

  {
    id: "order_1011",
    userId: 5,
    items: [
      {
        productId: 305,
        productName: "Lenovo Legion 5",
        quantity: 1,
        price: 58301,
        total: 58301,
      },
    ],
    totalAmount: 58301,
    status: "Shipped",
    date: new Date("2024-07-10T13:15:00Z").toLocaleString(),
  },

  {
    id: "order_1012",
    userId: 4,
    items: [
      {
        productId: 201,
        productName: "Samsung Galaxy A16 LTE",
        quantity: 1,
        price: 7790,
        total: 7790,
      },
    ],
    totalAmount: 7790,
    status: "Processing",
    date: new Date("2024-07-11T09:45:00Z").toLocaleString(),
  },

  {
    id: "order_1013",
    userId: 6,
    items: [
      {
        productId: 409,
        productName: "JBL Tune 520BT",
        quantity: 3,
        price: 1400,
        total: 4200,
      }, // 3 * 1400
    ],
    totalAmount: 4200,
    status: "Cancelled",
    date: new Date("2024-07-11T16:00:00Z").toLocaleString(),
  },

  {
    id: "order_1014",
    userId: 5,
    items: [
      {
        productId: 220,
        productName: "realme Note 50",
        quantity: 1,
        price: 4975,
        total: 4975,
      },
    ],
    totalAmount: 4975,
    status: "Delivered",
    date: new Date("2024-07-12T10:10:00Z").toLocaleString(),
  },

  {
    id: "order_1015",
    userId: 4,
    items: [
      {
        productId: 308,
        productName: "Lenovo LOQ 15IRX9 Gaming",
        quantity: 1,
        price: 51999,
        total: 51999,
      },
    ],
    totalAmount: 51999,
    status: "Processing",
    date: new Date("2024-07-12T14:20:00Z").toLocaleString(),
  },
];
function initializeData() {
  if (!localStorage.getItem("products")) {
    localStorage.setItem("products", JSON.stringify(initialProducts));
  }
  if (!localStorage.getItem("userData")) {
    localStorage.setItem("userData", JSON.stringify(userData));
  }
  if (!localStorage.getItem("orders")) {
    localStorage.setItem("orders", JSON.stringify(orders));
  }
}

initializeData();
